/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Light-DOM checkbox similar to ds-checkbox:
     * - Renders a native <input type="checkbox"> with a label
     * - Slot content keeps the marker-loss issue visible through 4.39.x; plain checkboxes are fine in 4.40.0
     */
    interface MyCheckbox {
        /**
          * @default true
         */
        "checked": boolean;
        /**
          * @default 'I agree'
         */
        "label": string;
        /**
          * @default 'agree'
         */
        "name": string;
        /**
          * @default 'yes'
         */
        "value": string;
    }
    /**
     * Light-DOM input similar to ds-input:
     * - Renders a native <input> in render()
     * - Plain Light-DOM input with an optional suffix slot
     * - Presence of slot content keeps the marker-loss issue visible through 4.39.x (fixed for plain inputs in 4.40.0)
     */
    interface MyInput {
        /**
          * @default 'email'
         */
        "name": string;
        /**
          * @default 'Enter email'
         */
        "placeholder": string;
        /**
          * @default 'test@example.com'
         */
        "value": string;
    }
    /**
     * Light-DOM radio similar to ds-radio:
     * - Renders a native <input type="radio"> with a label and optional suffix slot
     * - Slot content keeps the marker-loss issue visible through 4.39.x; plain radios are fine in 4.40.0
     */
    interface MyRadio {
        /**
          * @default true
         */
        "checked": boolean;
        /**
          * @default 'Option A'
         */
        "label": string;
        /**
          * @default 'choice'
         */
        "name": string;
        /**
          * @default 'option-a'
         */
        "value": string;
    }
    /**
     * Light-DOM select that mirrors the real ds-select flow:
     * - Renders a native <select> and a hidden slot container
     * - Moves slotted <option> nodes into the select after load (and on mutations)
     * - Syncs the selected value both ways
     */
    interface MySelect {
        /**
          * Simulated user id for the fetch
          * @default '42'
         */
        "userId": string;
        /**
          * Currently selected role
         */
        "value": string;
    }
}
declare global {
    /**
     * Light-DOM checkbox similar to ds-checkbox:
     * - Renders a native <input type="checkbox"> with a label
     * - Slot content keeps the marker-loss issue visible through 4.39.x; plain checkboxes are fine in 4.40.0
     */
    interface HTMLMyCheckboxElement extends Components.MyCheckbox, HTMLStencilElement {
    }
    var HTMLMyCheckboxElement: {
        prototype: HTMLMyCheckboxElement;
        new (): HTMLMyCheckboxElement;
    };
    /**
     * Light-DOM input similar to ds-input:
     * - Renders a native <input> in render()
     * - Plain Light-DOM input with an optional suffix slot
     * - Presence of slot content keeps the marker-loss issue visible through 4.39.x (fixed for plain inputs in 4.40.0)
     */
    interface HTMLMyInputElement extends Components.MyInput, HTMLStencilElement {
    }
    var HTMLMyInputElement: {
        prototype: HTMLMyInputElement;
        new (): HTMLMyInputElement;
    };
    /**
     * Light-DOM radio similar to ds-radio:
     * - Renders a native <input type="radio"> with a label and optional suffix slot
     * - Slot content keeps the marker-loss issue visible through 4.39.x; plain radios are fine in 4.40.0
     */
    interface HTMLMyRadioElement extends Components.MyRadio, HTMLStencilElement {
    }
    var HTMLMyRadioElement: {
        prototype: HTMLMyRadioElement;
        new (): HTMLMyRadioElement;
    };
    /**
     * Light-DOM select that mirrors the real ds-select flow:
     * - Renders a native <select> and a hidden slot container
     * - Moves slotted <option> nodes into the select after load (and on mutations)
     * - Syncs the selected value both ways
     */
    interface HTMLMySelectElement extends Components.MySelect, HTMLStencilElement {
    }
    var HTMLMySelectElement: {
        prototype: HTMLMySelectElement;
        new (): HTMLMySelectElement;
    };
    interface HTMLElementTagNameMap {
        "my-checkbox": HTMLMyCheckboxElement;
        "my-input": HTMLMyInputElement;
        "my-radio": HTMLMyRadioElement;
        "my-select": HTMLMySelectElement;
    }
}
declare namespace LocalJSX {
    /**
     * Light-DOM checkbox similar to ds-checkbox:
     * - Renders a native <input type="checkbox"> with a label
     * - Slot content keeps the marker-loss issue visible through 4.39.x; plain checkboxes are fine in 4.40.0
     */
    interface MyCheckbox {
        /**
          * @default true
         */
        "checked"?: boolean;
        /**
          * @default 'I agree'
         */
        "label"?: string;
        /**
          * @default 'agree'
         */
        "name"?: string;
        /**
          * @default 'yes'
         */
        "value"?: string;
    }
    /**
     * Light-DOM input similar to ds-input:
     * - Renders a native <input> in render()
     * - Plain Light-DOM input with an optional suffix slot
     * - Presence of slot content keeps the marker-loss issue visible through 4.39.x (fixed for plain inputs in 4.40.0)
     */
    interface MyInput {
        /**
          * @default 'email'
         */
        "name"?: string;
        /**
          * @default 'Enter email'
         */
        "placeholder"?: string;
        /**
          * @default 'test@example.com'
         */
        "value"?: string;
    }
    /**
     * Light-DOM radio similar to ds-radio:
     * - Renders a native <input type="radio"> with a label and optional suffix slot
     * - Slot content keeps the marker-loss issue visible through 4.39.x; plain radios are fine in 4.40.0
     */
    interface MyRadio {
        /**
          * @default true
         */
        "checked"?: boolean;
        /**
          * @default 'Option A'
         */
        "label"?: string;
        /**
          * @default 'choice'
         */
        "name"?: string;
        /**
          * @default 'option-a'
         */
        "value"?: string;
    }
    /**
     * Light-DOM select that mirrors the real ds-select flow:
     * - Renders a native <select> and a hidden slot container
     * - Moves slotted <option> nodes into the select after load (and on mutations)
     * - Syncs the selected value both ways
     */
    interface MySelect {
        /**
          * Simulated user id for the fetch
          * @default '42'
         */
        "userId"?: string;
        /**
          * Currently selected role
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "my-checkbox": MyCheckbox;
        "my-input": MyInput;
        "my-radio": MyRadio;
        "my-select": MySelect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Light-DOM checkbox similar to ds-checkbox:
             * - Renders a native <input type="checkbox"> with a label
             * - Slot content keeps the marker-loss issue visible through 4.39.x; plain checkboxes are fine in 4.40.0
             */
            "my-checkbox": LocalJSX.MyCheckbox & JSXBase.HTMLAttributes<HTMLMyCheckboxElement>;
            /**
             * Light-DOM input similar to ds-input:
             * - Renders a native <input> in render()
             * - Plain Light-DOM input with an optional suffix slot
             * - Presence of slot content keeps the marker-loss issue visible through 4.39.x (fixed for plain inputs in 4.40.0)
             */
            "my-input": LocalJSX.MyInput & JSXBase.HTMLAttributes<HTMLMyInputElement>;
            /**
             * Light-DOM radio similar to ds-radio:
             * - Renders a native <input type="radio"> with a label and optional suffix slot
             * - Slot content keeps the marker-loss issue visible through 4.39.x; plain radios are fine in 4.40.0
             */
            "my-radio": LocalJSX.MyRadio & JSXBase.HTMLAttributes<HTMLMyRadioElement>;
            /**
             * Light-DOM select that mirrors the real ds-select flow:
             * - Renders a native <select> and a hidden slot container
             * - Moves slotted <option> nodes into the select after load (and on mutations)
             * - Syncs the selected value both ways
             */
            "my-select": LocalJSX.MySelect & JSXBase.HTMLAttributes<HTMLMySelectElement>;
        }
    }
}
